fragment GrundlagenParts on Grundlagen {
  __typename
  title
  lead
  description
  image
  image_credit
  kapitel
  weight
  lesezeit
  stand
  tags
  draft
  body
}

fragment GlossarParts on Glossar {
  __typename
  title
  term_alt
  synonyme
  draft
  body
}

fragment MagazinParts on Magazin {
  __typename
  title
  date
  draft
  description
  image
  rubrik
  author
  tags
  body
}

fragment BundeslandParts on Bundesland {
  __typename
  title
  bundesland
  type
  lead
  description
  body
}

fragment Golf_kategorienParts on Golf_kategorien {
  __typename
  title
  kategorie
  type
  lead
  description
  body
}

fragment LocationsParts on Locations {
  __typename
  title
  date
  draft
  bundesland
  untertitel
  image
  kategorien
  greenfee_ab
  lochzahl
  schwierigkeit
  leihausruestung
  uebungsplatz
  driving_range
  restaurant
  hunde
  adresse
  website
  email
  telefon
  body
}
