//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  grundlagen: Grundlagen;
  grundlagenConnection: GrundlagenConnection;
  glossar: Glossar;
  glossarConnection: GlossarConnection;
  magazin: Magazin;
  magazinConnection: MagazinConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGrundlagenArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGrundlagenConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrundlagenFilter>;
};


export type QueryGlossarArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlossarConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossarFilter>;
};


export type QueryMagazinArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMagazinConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MagazinFilter>;
};

export type DocumentFilter = {
  grundlagen?: InputMaybe<GrundlagenFilter>;
  glossar?: InputMaybe<GlossarFilter>;
  magazin?: InputMaybe<MagazinFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Grundlagen | Glossar | Magazin | Folder;

export type Grundlagen = Node & Document & {
  __typename?: 'Grundlagen';
  title: Scalars['String']['output'];
  lead?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  image_credit?: Maybe<Scalars['String']['output']>;
  kapitel?: Maybe<Scalars['String']['output']>;
  weight?: Maybe<Scalars['Float']['output']>;
  lesezeit?: Maybe<Scalars['String']['output']>;
  stand?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GrundlagenFilter = {
  title?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  image_credit?: InputMaybe<StringFilter>;
  kapitel?: InputMaybe<StringFilter>;
  weight?: InputMaybe<NumberFilter>;
  lesezeit?: InputMaybe<StringFilter>;
  stand?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type GrundlagenConnectionEdges = {
  __typename?: 'GrundlagenConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Grundlagen>;
};

export type GrundlagenConnection = Connection & {
  __typename?: 'GrundlagenConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GrundlagenConnectionEdges>>>;
};

export type Glossar = Node & Document & {
  __typename?: 'Glossar';
  title: Scalars['String']['output'];
  term_alt?: Maybe<Scalars['String']['output']>;
  synonyme?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlossarFilter = {
  title?: InputMaybe<StringFilter>;
  term_alt?: InputMaybe<StringFilter>;
  synonyme?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type GlossarConnectionEdges = {
  __typename?: 'GlossarConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Glossar>;
};

export type GlossarConnection = Connection & {
  __typename?: 'GlossarConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlossarConnectionEdges>>>;
};

export type Magazin = Node & Document & {
  __typename?: 'Magazin';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  draft?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type MagazinFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type MagazinConnectionEdges = {
  __typename?: 'MagazinConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Magazin>;
};

export type MagazinConnection = Connection & {
  __typename?: 'MagazinConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MagazinConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGrundlagen: Grundlagen;
  createGrundlagen: Grundlagen;
  updateGlossar: Glossar;
  createGlossar: Glossar;
  updateMagazin: Magazin;
  createMagazin: Magazin;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGrundlagenArgs = {
  relativePath: Scalars['String']['input'];
  params: GrundlagenMutation;
};


export type MutationCreateGrundlagenArgs = {
  relativePath: Scalars['String']['input'];
  params: GrundlagenMutation;
};


export type MutationUpdateGlossarArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossarMutation;
};


export type MutationCreateGlossarArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossarMutation;
};


export type MutationUpdateMagazinArgs = {
  relativePath: Scalars['String']['input'];
  params: MagazinMutation;
};


export type MutationCreateMagazinArgs = {
  relativePath: Scalars['String']['input'];
  params: MagazinMutation;
};

export type DocumentUpdateMutation = {
  grundlagen?: InputMaybe<GrundlagenMutation>;
  glossar?: InputMaybe<GlossarMutation>;
  magazin?: InputMaybe<MagazinMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  grundlagen?: InputMaybe<GrundlagenMutation>;
  glossar?: InputMaybe<GlossarMutation>;
  magazin?: InputMaybe<MagazinMutation>;
};

export type GrundlagenMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  image_credit?: InputMaybe<Scalars['String']['input']>;
  kapitel?: InputMaybe<Scalars['String']['input']>;
  weight?: InputMaybe<Scalars['Float']['input']>;
  lesezeit?: InputMaybe<Scalars['String']['input']>;
  stand?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GlossarMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  term_alt?: InputMaybe<Scalars['String']['input']>;
  synonyme?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type MagazinMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GrundlagenPartsFragment = { __typename: 'Grundlagen', title: string, lead?: string | null, description?: string | null, image?: string | null, image_credit?: string | null, kapitel?: string | null, weight?: number | null, lesezeit?: string | null, stand?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type GlossarPartsFragment = { __typename: 'Glossar', title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null };

export type MagazinPartsFragment = { __typename: 'Magazin', title: string, date: string, draft?: boolean | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type GrundlagenQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GrundlagenQuery = { __typename?: 'Query', grundlagen: { __typename: 'Grundlagen', id: string, title: string, lead?: string | null, description?: string | null, image?: string | null, image_credit?: string | null, kapitel?: string | null, weight?: number | null, lesezeit?: string | null, stand?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GrundlagenConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrundlagenFilter>;
}>;


export type GrundlagenConnectionQuery = { __typename?: 'Query', grundlagenConnection: { __typename?: 'GrundlagenConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GrundlagenConnectionEdges', cursor: string, node?: { __typename: 'Grundlagen', id: string, title: string, lead?: string | null, description?: string | null, image?: string | null, image_credit?: string | null, kapitel?: string | null, weight?: number | null, lesezeit?: string | null, stand?: string | null, tags?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlossarQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlossarQuery = { __typename?: 'Query', glossar: { __typename: 'Glossar', id: string, title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GlossarConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossarFilter>;
}>;


export type GlossarConnectionQuery = { __typename?: 'Query', glossarConnection: { __typename?: 'GlossarConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlossarConnectionEdges', cursor: string, node?: { __typename: 'Glossar', id: string, title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MagazinQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MagazinQuery = { __typename?: 'Query', magazin: { __typename: 'Magazin', id: string, title: string, date: string, draft?: boolean | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MagazinConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MagazinFilter>;
}>;


export type MagazinConnectionQuery = { __typename?: 'Query', magazinConnection: { __typename?: 'MagazinConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MagazinConnectionEdges', cursor: string, node?: { __typename: 'Magazin', id: string, title: string, date: string, draft?: boolean | null, description?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const GrundlagenPartsFragmentDoc = gql`
    fragment GrundlagenParts on Grundlagen {
  __typename
  title
  lead
  description
  image
  image_credit
  kapitel
  weight
  lesezeit
  stand
  tags
  draft
  body
}
    `;
export const GlossarPartsFragmentDoc = gql`
    fragment GlossarParts on Glossar {
  __typename
  title
  term_alt
  synonyme
  draft
  body
}
    `;
export const MagazinPartsFragmentDoc = gql`
    fragment MagazinParts on Magazin {
  __typename
  title
  date
  draft
  description
  tags
  body
}
    `;
export const GrundlagenDocument = gql`
    query grundlagen($relativePath: String!) {
  grundlagen(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GrundlagenParts
  }
}
    ${GrundlagenPartsFragmentDoc}`;
export const GrundlagenConnectionDocument = gql`
    query grundlagenConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GrundlagenFilter) {
  grundlagenConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GrundlagenParts
      }
    }
  }
}
    ${GrundlagenPartsFragmentDoc}`;
export const GlossarDocument = gql`
    query glossar($relativePath: String!) {
  glossar(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlossarParts
  }
}
    ${GlossarPartsFragmentDoc}`;
export const GlossarConnectionDocument = gql`
    query glossarConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlossarFilter) {
  glossarConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlossarParts
      }
    }
  }
}
    ${GlossarPartsFragmentDoc}`;
export const MagazinDocument = gql`
    query magazin($relativePath: String!) {
  magazin(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MagazinParts
  }
}
    ${MagazinPartsFragmentDoc}`;
export const MagazinConnectionDocument = gql`
    query magazinConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MagazinFilter) {
  magazinConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MagazinParts
      }
    }
  }
}
    ${MagazinPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      grundlagen(variables: GrundlagenQueryVariables, options?: C): Promise<{data: GrundlagenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenQueryVariables, query: string}> {
        return requester<{data: GrundlagenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenQueryVariables, query: string}, GrundlagenQueryVariables>(GrundlagenDocument, variables, options);
      },
    grundlagenConnection(variables?: GrundlagenConnectionQueryVariables, options?: C): Promise<{data: GrundlagenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenConnectionQueryVariables, query: string}> {
        return requester<{data: GrundlagenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenConnectionQueryVariables, query: string}, GrundlagenConnectionQueryVariables>(GrundlagenConnectionDocument, variables, options);
      },
    glossar(variables: GlossarQueryVariables, options?: C): Promise<{data: GlossarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarQueryVariables, query: string}> {
        return requester<{data: GlossarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarQueryVariables, query: string}, GlossarQueryVariables>(GlossarDocument, variables, options);
      },
    glossarConnection(variables?: GlossarConnectionQueryVariables, options?: C): Promise<{data: GlossarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarConnectionQueryVariables, query: string}> {
        return requester<{data: GlossarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarConnectionQueryVariables, query: string}, GlossarConnectionQueryVariables>(GlossarConnectionDocument, variables, options);
      },
    magazin(variables: MagazinQueryVariables, options?: C): Promise<{data: MagazinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinQueryVariables, query: string}> {
        return requester<{data: MagazinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinQueryVariables, query: string}, MagazinQueryVariables>(MagazinDocument, variables, options);
      },
    magazinConnection(variables?: MagazinConnectionQueryVariables, options?: C): Promise<{data: MagazinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinConnectionQueryVariables, query: string}> {
        return requester<{data: MagazinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinConnectionQueryVariables, query: string}, MagazinConnectionQueryVariables>(MagazinConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  