//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  grundlagen: Grundlagen;
  grundlagenConnection: GrundlagenConnection;
  glossar: Glossar;
  glossarConnection: GlossarConnection;
  magazin: Magazin;
  magazinConnection: MagazinConnection;
  bundesland: Bundesland;
  bundeslandConnection: BundeslandConnection;
  golf_kategorien: Golf_Kategorien;
  golf_kategorienConnection: Golf_KategorienConnection;
  locations: Locations;
  locationsConnection: LocationsConnection;
  global: Global;
  globalConnection: GlobalConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGrundlagenArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGrundlagenConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrundlagenFilter>;
};


export type QueryGlossarArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlossarConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossarFilter>;
};


export type QueryMagazinArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMagazinConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MagazinFilter>;
};


export type QueryBundeslandArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBundeslandConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BundeslandFilter>;
};


export type QueryGolf_KategorienArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGolf_KategorienConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Golf_KategorienFilter>;
};


export type QueryLocationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationsFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};

export type DocumentFilter = {
  grundlagen?: InputMaybe<GrundlagenFilter>;
  glossar?: InputMaybe<GlossarFilter>;
  magazin?: InputMaybe<MagazinFilter>;
  bundesland?: InputMaybe<BundeslandFilter>;
  golf_kategorien?: InputMaybe<Golf_KategorienFilter>;
  locations?: InputMaybe<LocationsFilter>;
  global?: InputMaybe<GlobalFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = GrundlagenArtikel | GrundlagenUebersicht | Glossar | MagazinArtikel | MagazinUebersicht | Bundesland | Golf_Kategorien | Locations | GlobalHomepage | Folder;

export type GrundlagenArtikel = Node & Document & {
  __typename?: 'GrundlagenArtikel';
  draft?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  canonical?: Maybe<Scalars['String']['output']>;
  robots?: Maybe<Scalars['String']['output']>;
  hreflang?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  image_credit?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  lesezeit?: Maybe<Scalars['String']['output']>;
  h1?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  kapitel?: Maybe<Scalars['String']['output']>;
  weight?: Maybe<Scalars['Float']['output']>;
  stand?: Maybe<Scalars['String']['output']>;
  json_ld?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GrundlagenUebersichtKapitel_Liste = {
  __typename?: 'GrundlagenUebersichtKapitel_liste';
  id?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  nav_desc?: Maybe<Scalars['String']['output']>;
};

export type GrundlagenUebersicht = Node & Document & {
  __typename?: 'GrundlagenUebersicht';
  draft?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  canonical?: Maybe<Scalars['String']['output']>;
  robots?: Maybe<Scalars['String']['output']>;
  hreflang?: Maybe<Scalars['String']['output']>;
  eyebrow?: Maybe<Scalars['String']['output']>;
  h1?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  kapitel_liste?: Maybe<Array<Maybe<GrundlagenUebersichtKapitel_Liste>>>;
  json_ld?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Grundlagen = GrundlagenArtikel | GrundlagenUebersicht;

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type GrundlagenArtikelFilter = {
  draft?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  canonical?: InputMaybe<StringFilter>;
  robots?: InputMaybe<StringFilter>;
  hreflang?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  image_credit?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  lesezeit?: InputMaybe<StringFilter>;
  h1?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  tags?: InputMaybe<StringFilter>;
  kapitel?: InputMaybe<StringFilter>;
  weight?: InputMaybe<NumberFilter>;
  stand?: InputMaybe<StringFilter>;
  json_ld?: InputMaybe<StringFilter>;
};

export type GrundlagenUebersichtKapitel_ListeFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  nav_desc?: InputMaybe<StringFilter>;
};

export type GrundlagenUebersichtFilter = {
  draft?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  canonical?: InputMaybe<StringFilter>;
  robots?: InputMaybe<StringFilter>;
  hreflang?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  h1?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  kapitel_liste?: InputMaybe<GrundlagenUebersichtKapitel_ListeFilter>;
  json_ld?: InputMaybe<StringFilter>;
};

export type GrundlagenFilter = {
  artikel?: InputMaybe<GrundlagenArtikelFilter>;
  uebersicht?: InputMaybe<GrundlagenUebersichtFilter>;
};

export type GrundlagenConnectionEdges = {
  __typename?: 'GrundlagenConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Grundlagen>;
};

export type GrundlagenConnection = Connection & {
  __typename?: 'GrundlagenConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GrundlagenConnectionEdges>>>;
};

export type Glossar = Node & Document & {
  __typename?: 'Glossar';
  title: Scalars['String']['output'];
  term_alt?: Maybe<Scalars['String']['output']>;
  synonyme?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlossarFilter = {
  title?: InputMaybe<StringFilter>;
  term_alt?: InputMaybe<StringFilter>;
  synonyme?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type GlossarConnectionEdges = {
  __typename?: 'GlossarConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Glossar>;
};

export type GlossarConnection = Connection & {
  __typename?: 'GlossarConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlossarConnectionEdges>>>;
};

export type MagazinArtikel = Node & Document & {
  __typename?: 'MagazinArtikel';
  draft?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  canonical?: Maybe<Scalars['String']['output']>;
  robots?: Maybe<Scalars['String']['output']>;
  hreflang?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  lesezeit?: Maybe<Scalars['String']['output']>;
  h1?: Maybe<Scalars['String']['output']>;
  rubrik?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  json_ld?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MagazinUebersicht = Node & Document & {
  __typename?: 'MagazinUebersicht';
  draft?: Maybe<Scalars['Boolean']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  canonical?: Maybe<Scalars['String']['output']>;
  robots?: Maybe<Scalars['String']['output']>;
  hreflang?: Maybe<Scalars['String']['output']>;
  eyebrow?: Maybe<Scalars['String']['output']>;
  h1?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  json_ld?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Magazin = MagazinArtikel | MagazinUebersicht;

export type MagazinArtikelFilter = {
  draft?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  canonical?: InputMaybe<StringFilter>;
  robots?: InputMaybe<StringFilter>;
  hreflang?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  lesezeit?: InputMaybe<StringFilter>;
  h1?: InputMaybe<StringFilter>;
  rubrik?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  tags?: InputMaybe<StringFilter>;
  json_ld?: InputMaybe<StringFilter>;
};

export type MagazinUebersichtFilter = {
  draft?: InputMaybe<BooleanFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  canonical?: InputMaybe<StringFilter>;
  robots?: InputMaybe<StringFilter>;
  hreflang?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  h1?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  json_ld?: InputMaybe<StringFilter>;
};

export type MagazinFilter = {
  artikel?: InputMaybe<MagazinArtikelFilter>;
  uebersicht?: InputMaybe<MagazinUebersichtFilter>;
};

export type MagazinConnectionEdges = {
  __typename?: 'MagazinConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Magazin>;
};

export type MagazinConnection = Connection & {
  __typename?: 'MagazinConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MagazinConnectionEdges>>>;
};

export type Bundesland = Node & Document & {
  __typename?: 'Bundesland';
  title: Scalars['String']['output'];
  bundesland?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BundeslandFilter = {
  title?: InputMaybe<StringFilter>;
  bundesland?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BundeslandConnectionEdges = {
  __typename?: 'BundeslandConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bundesland>;
};

export type BundeslandConnection = Connection & {
  __typename?: 'BundeslandConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BundeslandConnectionEdges>>>;
};

export type Golf_Kategorien = Node & Document & {
  __typename?: 'Golf_kategorien';
  title: Scalars['String']['output'];
  kategorie?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Golf_KategorienFilter = {
  title?: InputMaybe<StringFilter>;
  kategorie?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Golf_KategorienConnectionEdges = {
  __typename?: 'Golf_kategorienConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Golf_Kategorien>;
};

export type Golf_KategorienConnection = Connection & {
  __typename?: 'Golf_kategorienConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Golf_KategorienConnectionEdges>>>;
};

export type Locations = Node & Document & {
  __typename?: 'Locations';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  bundesland?: Maybe<Scalars['String']['output']>;
  untertitel?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  kategorien?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  greenfee_ab?: Maybe<Scalars['Float']['output']>;
  lochzahl?: Maybe<Scalars['String']['output']>;
  schwierigkeit?: Maybe<Scalars['String']['output']>;
  leihausruestung?: Maybe<Scalars['String']['output']>;
  uebungsplatz?: Maybe<Scalars['String']['output']>;
  driving_range?: Maybe<Scalars['String']['output']>;
  restaurant?: Maybe<Scalars['String']['output']>;
  hunde?: Maybe<Scalars['String']['output']>;
  adresse?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  telefon?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocationsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  bundesland?: InputMaybe<StringFilter>;
  untertitel?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  kategorien?: InputMaybe<StringFilter>;
  greenfee_ab?: InputMaybe<NumberFilter>;
  lochzahl?: InputMaybe<StringFilter>;
  schwierigkeit?: InputMaybe<StringFilter>;
  leihausruestung?: InputMaybe<StringFilter>;
  uebungsplatz?: InputMaybe<StringFilter>;
  driving_range?: InputMaybe<StringFilter>;
  restaurant?: InputMaybe<StringFilter>;
  hunde?: InputMaybe<StringFilter>;
  adresse?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  telefon?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type LocationsConnectionEdges = {
  __typename?: 'LocationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Locations>;
};

export type LocationsConnection = Connection & {
  __typename?: 'LocationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocationsConnectionEdges>>>;
};

export type GlobalHomepageQuotes = {
  __typename?: 'GlobalHomepageQuotes';
  text?: Maybe<Scalars['String']['output']>;
  cite?: Maybe<Scalars['String']['output']>;
};

export type GlobalHomepageGrundlagen_Karten = {
  __typename?: 'GlobalHomepageGrundlagen_karten';
  icon?: Maybe<Scalars['String']['output']>;
  titel?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type GlobalHomepage = Node & Document & {
  __typename?: 'GlobalHomepage';
  title: Scalars['String']['output'];
  hero_tag?: Maybe<Scalars['String']['output']>;
  hero_title?: Maybe<Scalars['String']['output']>;
  hero_sub?: Maybe<Scalars['String']['output']>;
  cta_primary_text?: Maybe<Scalars['String']['output']>;
  cta_primary_url?: Maybe<Scalars['String']['output']>;
  cta_secondary_text?: Maybe<Scalars['String']['output']>;
  cta_secondary_url?: Maybe<Scalars['String']['output']>;
  quotes?: Maybe<Array<Maybe<GlobalHomepageQuotes>>>;
  grundlagen_label?: Maybe<Scalars['String']['output']>;
  grundlagen_title?: Maybe<Scalars['String']['output']>;
  grundlagen_intro?: Maybe<Scalars['String']['output']>;
  grundlagen_karten?: Maybe<Array<Maybe<GlobalHomepageGrundlagen_Karten>>>;
  locations_label?: Maybe<Scalars['String']['output']>;
  locations_title?: Maybe<Scalars['String']['output']>;
  locations_intro?: Maybe<Scalars['String']['output']>;
  magazin_label?: Maybe<Scalars['String']['output']>;
  magazin_title?: Maybe<Scalars['String']['output']>;
  magazin_intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Global = GlobalHomepage;

export type GlobalHomepageQuotesFilter = {
  text?: InputMaybe<StringFilter>;
  cite?: InputMaybe<StringFilter>;
};

export type GlobalHomepageGrundlagen_KartenFilter = {
  icon?: InputMaybe<StringFilter>;
  titel?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type GlobalHomepageFilter = {
  title?: InputMaybe<StringFilter>;
  hero_tag?: InputMaybe<StringFilter>;
  hero_title?: InputMaybe<StringFilter>;
  hero_sub?: InputMaybe<StringFilter>;
  cta_primary_text?: InputMaybe<StringFilter>;
  cta_primary_url?: InputMaybe<StringFilter>;
  cta_secondary_text?: InputMaybe<StringFilter>;
  cta_secondary_url?: InputMaybe<StringFilter>;
  quotes?: InputMaybe<GlobalHomepageQuotesFilter>;
  grundlagen_label?: InputMaybe<StringFilter>;
  grundlagen_title?: InputMaybe<StringFilter>;
  grundlagen_intro?: InputMaybe<StringFilter>;
  grundlagen_karten?: InputMaybe<GlobalHomepageGrundlagen_KartenFilter>;
  locations_label?: InputMaybe<StringFilter>;
  locations_title?: InputMaybe<StringFilter>;
  locations_intro?: InputMaybe<StringFilter>;
  magazin_label?: InputMaybe<StringFilter>;
  magazin_title?: InputMaybe<StringFilter>;
  magazin_intro?: InputMaybe<StringFilter>;
};

export type GlobalFilter = {
  homepage?: InputMaybe<GlobalHomepageFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGrundlagen: Grundlagen;
  createGrundlagen: Grundlagen;
  updateGlossar: Glossar;
  createGlossar: Glossar;
  updateMagazin: Magazin;
  createMagazin: Magazin;
  updateBundesland: Bundesland;
  createBundesland: Bundesland;
  updateGolf_kategorien: Golf_Kategorien;
  createGolf_kategorien: Golf_Kategorien;
  updateLocations: Locations;
  createLocations: Locations;
  updateGlobal: Global;
  createGlobal: Global;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGrundlagenArgs = {
  relativePath: Scalars['String']['input'];
  params: GrundlagenMutation;
};


export type MutationCreateGrundlagenArgs = {
  relativePath: Scalars['String']['input'];
  params: GrundlagenMutation;
};


export type MutationUpdateGlossarArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossarMutation;
};


export type MutationCreateGlossarArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossarMutation;
};


export type MutationUpdateMagazinArgs = {
  relativePath: Scalars['String']['input'];
  params: MagazinMutation;
};


export type MutationCreateMagazinArgs = {
  relativePath: Scalars['String']['input'];
  params: MagazinMutation;
};


export type MutationUpdateBundeslandArgs = {
  relativePath: Scalars['String']['input'];
  params: BundeslandMutation;
};


export type MutationCreateBundeslandArgs = {
  relativePath: Scalars['String']['input'];
  params: BundeslandMutation;
};


export type MutationUpdateGolf_KategorienArgs = {
  relativePath: Scalars['String']['input'];
  params: Golf_KategorienMutation;
};


export type MutationCreateGolf_KategorienArgs = {
  relativePath: Scalars['String']['input'];
  params: Golf_KategorienMutation;
};


export type MutationUpdateLocationsArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationsMutation;
};


export type MutationCreateLocationsArgs = {
  relativePath: Scalars['String']['input'];
  params: LocationsMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};

export type DocumentUpdateMutation = {
  grundlagen?: InputMaybe<GrundlagenMutation>;
  glossar?: InputMaybe<GlossarMutation>;
  magazin?: InputMaybe<MagazinMutation>;
  bundesland?: InputMaybe<BundeslandMutation>;
  golf_kategorien?: InputMaybe<Golf_KategorienMutation>;
  locations?: InputMaybe<LocationsMutation>;
  global?: InputMaybe<GlobalMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  grundlagen?: InputMaybe<GrundlagenMutation>;
  glossar?: InputMaybe<GlossarMutation>;
  magazin?: InputMaybe<MagazinMutation>;
  bundesland?: InputMaybe<BundeslandMutation>;
  golf_kategorien?: InputMaybe<Golf_KategorienMutation>;
  locations?: InputMaybe<LocationsMutation>;
  global?: InputMaybe<GlobalMutation>;
};

export type GrundlagenArtikelMutation = {
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  canonical?: InputMaybe<Scalars['String']['input']>;
  robots?: InputMaybe<Scalars['String']['input']>;
  hreflang?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  image_credit?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  lesezeit?: InputMaybe<Scalars['String']['input']>;
  h1?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  kapitel?: InputMaybe<Scalars['String']['input']>;
  weight?: InputMaybe<Scalars['Float']['input']>;
  stand?: InputMaybe<Scalars['String']['input']>;
  json_ld?: InputMaybe<Scalars['String']['input']>;
};

export type GrundlagenUebersichtKapitel_ListeMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  nav_desc?: InputMaybe<Scalars['String']['input']>;
};

export type GrundlagenUebersichtMutation = {
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  canonical?: InputMaybe<Scalars['String']['input']>;
  robots?: InputMaybe<Scalars['String']['input']>;
  hreflang?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  h1?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  kapitel_liste?: InputMaybe<Array<InputMaybe<GrundlagenUebersichtKapitel_ListeMutation>>>;
  json_ld?: InputMaybe<Scalars['String']['input']>;
};

export type GrundlagenMutation = {
  artikel?: InputMaybe<GrundlagenArtikelMutation>;
  uebersicht?: InputMaybe<GrundlagenUebersichtMutation>;
};

export type GlossarMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  term_alt?: InputMaybe<Scalars['String']['input']>;
  synonyme?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type MagazinArtikelMutation = {
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  canonical?: InputMaybe<Scalars['String']['input']>;
  robots?: InputMaybe<Scalars['String']['input']>;
  hreflang?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  lesezeit?: InputMaybe<Scalars['String']['input']>;
  h1?: InputMaybe<Scalars['String']['input']>;
  rubrik?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  json_ld?: InputMaybe<Scalars['String']['input']>;
};

export type MagazinUebersichtMutation = {
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  canonical?: InputMaybe<Scalars['String']['input']>;
  robots?: InputMaybe<Scalars['String']['input']>;
  hreflang?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  h1?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  json_ld?: InputMaybe<Scalars['String']['input']>;
};

export type MagazinMutation = {
  artikel?: InputMaybe<MagazinArtikelMutation>;
  uebersicht?: InputMaybe<MagazinUebersichtMutation>;
};

export type BundeslandMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  bundesland?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Golf_KategorienMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  kategorie?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type LocationsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  bundesland?: InputMaybe<Scalars['String']['input']>;
  untertitel?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  kategorien?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  greenfee_ab?: InputMaybe<Scalars['Float']['input']>;
  lochzahl?: InputMaybe<Scalars['String']['input']>;
  schwierigkeit?: InputMaybe<Scalars['String']['input']>;
  leihausruestung?: InputMaybe<Scalars['String']['input']>;
  uebungsplatz?: InputMaybe<Scalars['String']['input']>;
  driving_range?: InputMaybe<Scalars['String']['input']>;
  restaurant?: InputMaybe<Scalars['String']['input']>;
  hunde?: InputMaybe<Scalars['String']['input']>;
  adresse?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  telefon?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GlobalHomepageQuotesMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  cite?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalHomepageGrundlagen_KartenMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  titel?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalHomepageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  hero_tag?: InputMaybe<Scalars['String']['input']>;
  hero_title?: InputMaybe<Scalars['String']['input']>;
  hero_sub?: InputMaybe<Scalars['String']['input']>;
  cta_primary_text?: InputMaybe<Scalars['String']['input']>;
  cta_primary_url?: InputMaybe<Scalars['String']['input']>;
  cta_secondary_text?: InputMaybe<Scalars['String']['input']>;
  cta_secondary_url?: InputMaybe<Scalars['String']['input']>;
  quotes?: InputMaybe<Array<InputMaybe<GlobalHomepageQuotesMutation>>>;
  grundlagen_label?: InputMaybe<Scalars['String']['input']>;
  grundlagen_title?: InputMaybe<Scalars['String']['input']>;
  grundlagen_intro?: InputMaybe<Scalars['String']['input']>;
  grundlagen_karten?: InputMaybe<Array<InputMaybe<GlobalHomepageGrundlagen_KartenMutation>>>;
  locations_label?: InputMaybe<Scalars['String']['input']>;
  locations_title?: InputMaybe<Scalars['String']['input']>;
  locations_intro?: InputMaybe<Scalars['String']['input']>;
  magazin_label?: InputMaybe<Scalars['String']['input']>;
  magazin_title?: InputMaybe<Scalars['String']['input']>;
  magazin_intro?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  homepage?: InputMaybe<GlobalHomepageMutation>;
};

type GrundlagenParts_GrundlagenArtikel_Fragment = { __typename: 'GrundlagenArtikel', draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, image_credit?: string | null, date?: string | null, lesezeit?: string | null, h1?: string | null, lead?: string | null, body?: any | null, tags?: Array<string | null> | null, kapitel?: string | null, weight?: number | null, stand?: string | null, json_ld?: string | null };

type GrundlagenParts_GrundlagenUebersicht_Fragment = { __typename: 'GrundlagenUebersicht', draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null, kapitel_liste?: Array<{ __typename: 'GrundlagenUebersichtKapitel_liste', id?: string | null, label?: string | null, title?: string | null, desc?: string | null, nav_desc?: string | null } | null> | null };

export type GrundlagenPartsFragment = GrundlagenParts_GrundlagenArtikel_Fragment | GrundlagenParts_GrundlagenUebersicht_Fragment;

export type GlossarPartsFragment = { __typename: 'Glossar', title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null };

type MagazinParts_MagazinArtikel_Fragment = { __typename: 'MagazinArtikel', draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, date: string, lesezeit?: string | null, h1?: string | null, rubrik?: string | null, author?: string | null, body?: any | null, tags?: Array<string | null> | null, json_ld?: string | null };

type MagazinParts_MagazinUebersicht_Fragment = { __typename: 'MagazinUebersicht', draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null };

export type MagazinPartsFragment = MagazinParts_MagazinArtikel_Fragment | MagazinParts_MagazinUebersicht_Fragment;

export type BundeslandPartsFragment = { __typename: 'Bundesland', title: string, bundesland?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null };

export type Golf_KategorienPartsFragment = { __typename: 'Golf_kategorien', title: string, kategorie?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null };

export type LocationsPartsFragment = { __typename: 'Locations', title: string, date?: string | null, draft?: boolean | null, bundesland?: string | null, untertitel?: string | null, image?: string | null, kategorien?: Array<string | null> | null, greenfee_ab?: number | null, lochzahl?: string | null, schwierigkeit?: string | null, leihausruestung?: string | null, uebungsplatz?: string | null, driving_range?: string | null, restaurant?: string | null, hunde?: string | null, adresse?: string | null, website?: string | null, email?: string | null, telefon?: string | null, body?: any | null };

export type GlobalPartsFragment = { __typename: 'GlobalHomepage', title: string, hero_tag?: string | null, hero_title?: string | null, hero_sub?: string | null, cta_primary_text?: string | null, cta_primary_url?: string | null, cta_secondary_text?: string | null, cta_secondary_url?: string | null, grundlagen_label?: string | null, grundlagen_title?: string | null, grundlagen_intro?: string | null, locations_label?: string | null, locations_title?: string | null, locations_intro?: string | null, magazin_label?: string | null, magazin_title?: string | null, magazin_intro?: string | null, quotes?: Array<{ __typename: 'GlobalHomepageQuotes', text?: string | null, cite?: string | null } | null> | null, grundlagen_karten?: Array<{ __typename: 'GlobalHomepageGrundlagen_karten', icon?: string | null, titel?: string | null, text?: string | null, url?: string | null } | null> | null };

export type GrundlagenQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GrundlagenQuery = { __typename?: 'Query', grundlagen: { __typename: 'GrundlagenArtikel', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, image_credit?: string | null, date?: string | null, lesezeit?: string | null, h1?: string | null, lead?: string | null, body?: any | null, tags?: Array<string | null> | null, kapitel?: string | null, weight?: number | null, stand?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename: 'GrundlagenUebersicht', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kapitel_liste?: Array<{ __typename: 'GrundlagenUebersichtKapitel_liste', id?: string | null, label?: string | null, title?: string | null, desc?: string | null, nav_desc?: string | null } | null> | null } };

export type GrundlagenConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GrundlagenFilter>;
}>;


export type GrundlagenConnectionQuery = { __typename?: 'Query', grundlagenConnection: { __typename?: 'GrundlagenConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GrundlagenConnectionEdges', cursor: string, node?: { __typename: 'GrundlagenArtikel', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, image_credit?: string | null, date?: string | null, lesezeit?: string | null, h1?: string | null, lead?: string | null, body?: any | null, tags?: Array<string | null> | null, kapitel?: string | null, weight?: number | null, stand?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename: 'GrundlagenUebersicht', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, kapitel_liste?: Array<{ __typename: 'GrundlagenUebersichtKapitel_liste', id?: string | null, label?: string | null, title?: string | null, desc?: string | null, nav_desc?: string | null } | null> | null } | null } | null> | null } };

export type GlossarQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlossarQuery = { __typename?: 'Query', glossar: { __typename: 'Glossar', id: string, title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GlossarConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossarFilter>;
}>;


export type GlossarConnectionQuery = { __typename?: 'Query', glossarConnection: { __typename?: 'GlossarConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlossarConnectionEdges', cursor: string, node?: { __typename: 'Glossar', id: string, title: string, term_alt?: string | null, synonyme?: string | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MagazinQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MagazinQuery = { __typename?: 'Query', magazin: { __typename: 'MagazinArtikel', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, date: string, lesezeit?: string | null, h1?: string | null, rubrik?: string | null, author?: string | null, body?: any | null, tags?: Array<string | null> | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename: 'MagazinUebersicht', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MagazinConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MagazinFilter>;
}>;


export type MagazinConnectionQuery = { __typename?: 'Query', magazinConnection: { __typename?: 'MagazinConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MagazinConnectionEdges', cursor: string, node?: { __typename: 'MagazinArtikel', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, image?: string | null, date: string, lesezeit?: string | null, h1?: string | null, rubrik?: string | null, author?: string | null, body?: any | null, tags?: Array<string | null> | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename: 'MagazinUebersicht', id: string, draft?: boolean | null, title: string, description?: string | null, slug?: string | null, canonical?: string | null, robots?: string | null, hreflang?: string | null, eyebrow?: string | null, h1?: string | null, lead?: string | null, json_ld?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BundeslandQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BundeslandQuery = { __typename?: 'Query', bundesland: { __typename: 'Bundesland', id: string, title: string, bundesland?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BundeslandConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BundeslandFilter>;
}>;


export type BundeslandConnectionQuery = { __typename?: 'Query', bundeslandConnection: { __typename?: 'BundeslandConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BundeslandConnectionEdges', cursor: string, node?: { __typename: 'Bundesland', id: string, title: string, bundesland?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Golf_KategorienQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Golf_KategorienQuery = { __typename?: 'Query', golf_kategorien: { __typename: 'Golf_kategorien', id: string, title: string, kategorie?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Golf_KategorienConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Golf_KategorienFilter>;
}>;


export type Golf_KategorienConnectionQuery = { __typename?: 'Query', golf_kategorienConnection: { __typename?: 'Golf_kategorienConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Golf_kategorienConnectionEdges', cursor: string, node?: { __typename: 'Golf_kategorien', id: string, title: string, kategorie?: string | null, type?: string | null, lead?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LocationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LocationsQuery = { __typename?: 'Query', locations: { __typename: 'Locations', id: string, title: string, date?: string | null, draft?: boolean | null, bundesland?: string | null, untertitel?: string | null, image?: string | null, kategorien?: Array<string | null> | null, greenfee_ab?: number | null, lochzahl?: string | null, schwierigkeit?: string | null, leihausruestung?: string | null, uebungsplatz?: string | null, driving_range?: string | null, restaurant?: string | null, hunde?: string | null, adresse?: string | null, website?: string | null, email?: string | null, telefon?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LocationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocationsFilter>;
}>;


export type LocationsConnectionQuery = { __typename?: 'Query', locationsConnection: { __typename?: 'LocationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LocationsConnectionEdges', cursor: string, node?: { __typename: 'Locations', id: string, title: string, date?: string | null, draft?: boolean | null, bundesland?: string | null, untertitel?: string | null, image?: string | null, kategorien?: Array<string | null> | null, greenfee_ab?: number | null, lochzahl?: string | null, schwierigkeit?: string | null, leihausruestung?: string | null, uebungsplatz?: string | null, driving_range?: string | null, restaurant?: string | null, hunde?: string | null, adresse?: string | null, website?: string | null, email?: string | null, telefon?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'GlobalHomepage', id: string, title: string, hero_tag?: string | null, hero_title?: string | null, hero_sub?: string | null, cta_primary_text?: string | null, cta_primary_url?: string | null, cta_secondary_text?: string | null, cta_secondary_url?: string | null, grundlagen_label?: string | null, grundlagen_title?: string | null, grundlagen_intro?: string | null, locations_label?: string | null, locations_title?: string | null, locations_intro?: string | null, magazin_label?: string | null, magazin_title?: string | null, magazin_intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quotes?: Array<{ __typename: 'GlobalHomepageQuotes', text?: string | null, cite?: string | null } | null> | null, grundlagen_karten?: Array<{ __typename: 'GlobalHomepageGrundlagen_karten', icon?: string | null, titel?: string | null, text?: string | null, url?: string | null } | null> | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'GlobalHomepage', id: string, title: string, hero_tag?: string | null, hero_title?: string | null, hero_sub?: string | null, cta_primary_text?: string | null, cta_primary_url?: string | null, cta_secondary_text?: string | null, cta_secondary_url?: string | null, grundlagen_label?: string | null, grundlagen_title?: string | null, grundlagen_intro?: string | null, locations_label?: string | null, locations_title?: string | null, locations_intro?: string | null, magazin_label?: string | null, magazin_title?: string | null, magazin_intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, quotes?: Array<{ __typename: 'GlobalHomepageQuotes', text?: string | null, cite?: string | null } | null> | null, grundlagen_karten?: Array<{ __typename: 'GlobalHomepageGrundlagen_karten', icon?: string | null, titel?: string | null, text?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export const GrundlagenPartsFragmentDoc = gql`
    fragment GrundlagenParts on Grundlagen {
  __typename
  ... on GrundlagenArtikel {
    draft
    title
    description
    slug
    canonical
    robots
    hreflang
    image
    image_credit
    date
    lesezeit
    h1
    lead
    body
    tags
    kapitel
    weight
    stand
    json_ld
  }
  ... on GrundlagenUebersicht {
    draft
    title
    description
    slug
    canonical
    robots
    hreflang
    eyebrow
    h1
    lead
    kapitel_liste {
      __typename
      id
      label
      title
      desc
      nav_desc
    }
    json_ld
  }
}
    `;
export const GlossarPartsFragmentDoc = gql`
    fragment GlossarParts on Glossar {
  __typename
  title
  term_alt
  synonyme
  draft
  body
}
    `;
export const MagazinPartsFragmentDoc = gql`
    fragment MagazinParts on Magazin {
  __typename
  ... on MagazinArtikel {
    draft
    title
    description
    slug
    canonical
    robots
    hreflang
    image
    date
    lesezeit
    h1
    rubrik
    author
    body
    tags
    json_ld
  }
  ... on MagazinUebersicht {
    draft
    title
    description
    slug
    canonical
    robots
    hreflang
    eyebrow
    h1
    lead
    json_ld
  }
}
    `;
export const BundeslandPartsFragmentDoc = gql`
    fragment BundeslandParts on Bundesland {
  __typename
  title
  bundesland
  type
  lead
  description
  body
}
    `;
export const Golf_KategorienPartsFragmentDoc = gql`
    fragment Golf_kategorienParts on Golf_kategorien {
  __typename
  title
  kategorie
  type
  lead
  description
  body
}
    `;
export const LocationsPartsFragmentDoc = gql`
    fragment LocationsParts on Locations {
  __typename
  title
  date
  draft
  bundesland
  untertitel
  image
  kategorien
  greenfee_ab
  lochzahl
  schwierigkeit
  leihausruestung
  uebungsplatz
  driving_range
  restaurant
  hunde
  adresse
  website
  email
  telefon
  body
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  ... on GlobalHomepage {
    title
    hero_tag
    hero_title
    hero_sub
    cta_primary_text
    cta_primary_url
    cta_secondary_text
    cta_secondary_url
    quotes {
      __typename
      text
      cite
    }
    grundlagen_label
    grundlagen_title
    grundlagen_intro
    grundlagen_karten {
      __typename
      icon
      titel
      text
      url
    }
    locations_label
    locations_title
    locations_intro
    magazin_label
    magazin_title
    magazin_intro
  }
}
    `;
export const GrundlagenDocument = gql`
    query grundlagen($relativePath: String!) {
  grundlagen(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GrundlagenParts
  }
}
    ${GrundlagenPartsFragmentDoc}`;
export const GrundlagenConnectionDocument = gql`
    query grundlagenConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GrundlagenFilter) {
  grundlagenConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GrundlagenParts
      }
    }
  }
}
    ${GrundlagenPartsFragmentDoc}`;
export const GlossarDocument = gql`
    query glossar($relativePath: String!) {
  glossar(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlossarParts
  }
}
    ${GlossarPartsFragmentDoc}`;
export const GlossarConnectionDocument = gql`
    query glossarConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlossarFilter) {
  glossarConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlossarParts
      }
    }
  }
}
    ${GlossarPartsFragmentDoc}`;
export const MagazinDocument = gql`
    query magazin($relativePath: String!) {
  magazin(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MagazinParts
  }
}
    ${MagazinPartsFragmentDoc}`;
export const MagazinConnectionDocument = gql`
    query magazinConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MagazinFilter) {
  magazinConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MagazinParts
      }
    }
  }
}
    ${MagazinPartsFragmentDoc}`;
export const BundeslandDocument = gql`
    query bundesland($relativePath: String!) {
  bundesland(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BundeslandParts
  }
}
    ${BundeslandPartsFragmentDoc}`;
export const BundeslandConnectionDocument = gql`
    query bundeslandConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BundeslandFilter) {
  bundeslandConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BundeslandParts
      }
    }
  }
}
    ${BundeslandPartsFragmentDoc}`;
export const Golf_KategorienDocument = gql`
    query golf_kategorien($relativePath: String!) {
  golf_kategorien(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Golf_kategorienParts
  }
}
    ${Golf_KategorienPartsFragmentDoc}`;
export const Golf_KategorienConnectionDocument = gql`
    query golf_kategorienConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Golf_kategorienFilter) {
  golf_kategorienConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Golf_kategorienParts
      }
    }
  }
}
    ${Golf_KategorienPartsFragmentDoc}`;
export const LocationsDocument = gql`
    query locations($relativePath: String!) {
  locations(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocationsParts
  }
}
    ${LocationsPartsFragmentDoc}`;
export const LocationsConnectionDocument = gql`
    query locationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocationsFilter) {
  locationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocationsParts
      }
    }
  }
}
    ${LocationsPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      grundlagen(variables: GrundlagenQueryVariables, options?: C): Promise<{data: GrundlagenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenQueryVariables, query: string}> {
        return requester<{data: GrundlagenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenQueryVariables, query: string}, GrundlagenQueryVariables>(GrundlagenDocument, variables, options);
      },
    grundlagenConnection(variables?: GrundlagenConnectionQueryVariables, options?: C): Promise<{data: GrundlagenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenConnectionQueryVariables, query: string}> {
        return requester<{data: GrundlagenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GrundlagenConnectionQueryVariables, query: string}, GrundlagenConnectionQueryVariables>(GrundlagenConnectionDocument, variables, options);
      },
    glossar(variables: GlossarQueryVariables, options?: C): Promise<{data: GlossarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarQueryVariables, query: string}> {
        return requester<{data: GlossarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarQueryVariables, query: string}, GlossarQueryVariables>(GlossarDocument, variables, options);
      },
    glossarConnection(variables?: GlossarConnectionQueryVariables, options?: C): Promise<{data: GlossarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarConnectionQueryVariables, query: string}> {
        return requester<{data: GlossarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossarConnectionQueryVariables, query: string}, GlossarConnectionQueryVariables>(GlossarConnectionDocument, variables, options);
      },
    magazin(variables: MagazinQueryVariables, options?: C): Promise<{data: MagazinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinQueryVariables, query: string}> {
        return requester<{data: MagazinQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinQueryVariables, query: string}, MagazinQueryVariables>(MagazinDocument, variables, options);
      },
    magazinConnection(variables?: MagazinConnectionQueryVariables, options?: C): Promise<{data: MagazinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinConnectionQueryVariables, query: string}> {
        return requester<{data: MagazinConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MagazinConnectionQueryVariables, query: string}, MagazinConnectionQueryVariables>(MagazinConnectionDocument, variables, options);
      },
    bundesland(variables: BundeslandQueryVariables, options?: C): Promise<{data: BundeslandQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BundeslandQueryVariables, query: string}> {
        return requester<{data: BundeslandQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BundeslandQueryVariables, query: string}, BundeslandQueryVariables>(BundeslandDocument, variables, options);
      },
    bundeslandConnection(variables?: BundeslandConnectionQueryVariables, options?: C): Promise<{data: BundeslandConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BundeslandConnectionQueryVariables, query: string}> {
        return requester<{data: BundeslandConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BundeslandConnectionQueryVariables, query: string}, BundeslandConnectionQueryVariables>(BundeslandConnectionDocument, variables, options);
      },
    golf_kategorien(variables: Golf_KategorienQueryVariables, options?: C): Promise<{data: Golf_KategorienQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Golf_KategorienQueryVariables, query: string}> {
        return requester<{data: Golf_KategorienQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Golf_KategorienQueryVariables, query: string}, Golf_KategorienQueryVariables>(Golf_KategorienDocument, variables, options);
      },
    golf_kategorienConnection(variables?: Golf_KategorienConnectionQueryVariables, options?: C): Promise<{data: Golf_KategorienConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Golf_KategorienConnectionQueryVariables, query: string}> {
        return requester<{data: Golf_KategorienConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Golf_KategorienConnectionQueryVariables, query: string}, Golf_KategorienConnectionQueryVariables>(Golf_KategorienConnectionDocument, variables, options);
      },
    locations(variables: LocationsQueryVariables, options?: C): Promise<{data: LocationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationsQueryVariables, query: string}> {
        return requester<{data: LocationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationsQueryVariables, query: string}, LocationsQueryVariables>(LocationsDocument, variables, options);
      },
    locationsConnection(variables?: LocationsConnectionQueryVariables, options?: C): Promise<{data: LocationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationsConnectionQueryVariables, query: string}> {
        return requester<{data: LocationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocationsConnectionQueryVariables, query: string}, LocationsConnectionQueryVariables>(LocationsConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  